var utils = require('../utils');

var Lambda = function(app, opts) {
  utils.checkIdentifier(opts.name, 'lambda name');
  this.name = opts.name;
  this.description = opts.description || (opts.name + ' (generated by Lambdafai)');
  this.ram = opts.ram || 128;
  this.timeout = opts.timeout || 10;
  this.routes = [];
};

Lambda.prototype.get = function(path, handler) {
  this.routes.push({method: 'GET', path: path, handler: handler });
}

Lambda.prototype.post = function(path, handler) {
  this.routes.push({method: 'POST', path: path, handler: handler });
}

Lambda.prototype.put = function(path, handler) {
  this.routes.push({method: 'PUT', path: path, handler: handler });
}

Lambda.prototype.head = function(path, handler) {
  this.routes.push({method: 'HEAD', path: path, handler: handler });
}

Lambda.prototype.delete = function(path, handler) {
  this.routes.push({method: 'DELETE', path: path, handler: handler });
}

Lambda.prototype.options = function(path, handler) {
  this.routes.push({method: 'OPTIONS', path: path, handler: handler });
}

module.exports = Lambda;
